apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment-green
spec:
  replicas: 4
  selector:
    matchLabels:
      app: capstone
      role: green
  template:
    metadata:
      labels:
        app: capstone
        role: green
    spec:
      containers:
        - name: nginx
          image: moheshchandran/nginx:green
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
